package com.example.demo.Controller;

import com.example.demo.Models.daily;
import com.example.demo.Models.DaiLyModel.DaiLyBuilder;
import com.example.demo.Models.DaiLyModel.DaiLyConcreteBuilder;
import com.example.demo.Repository.DaiLyRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/daily") //http://localhost:8080/daily/hello
public class DaiLyController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DaiLyRepository daiLyRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewDaiLy (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        DaiLyBuilder buider = new DaiLyConcreteBuilder()
                .setMaDaiLy(1)
                .setTenDaiLy(name)
                .setDiaChi("HaNoi")
                .setDienThoai("0123456789")
                .setMaLoaiDaiLy(1)
                .setMaQuan(1)
                .setEmail(email)
                .setSoNo(0)
                .setNgayTiepNhan("2021-01-01");

        daily n = buider.build();

        daiLyRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<daily> getAllDaiLy() {
        // This returns a JSON or XML with the users
        return daiLyRepository.findAll();
    }

    @GetMapping(path="/byId")
    public @ResponseBody Iterable<daily> getDaiLyById(@RequestParam int maDaiLy) {
        return daiLyRepository.getDaiLyById(maDaiLy);
    }

    @GetMapping(path="/all1")
    public @ResponseBody Iterable<daily> getAllDaiLy1(@RequestParam String tendaily) {
        return daiLyRepository.getAllDaiLyByTenDaiLy(tendaily);
    }
}

